applications/empleados/urls.py
from django.urls import path
from . import views

app_name="empleados_app"

urlpatterns = [
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'),
    path(
        'listar-by-area/<shorname>',
         views.ListByAreaEmpleado.as_view(),
         name='empleados_area'),
    path(
        'lista-empleados-admin',
         views.ListaEmpleadosAdmin.as_view(),
         name='empleados_admin'),
    path('buscar-empleado', views.ListEmpleadosByKwords.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleados.as_view()),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'),
    path(
        'add-empleado/',
         views.EmpleadoCreateView.as_view(),
         name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
    path('', views.InicioView.as_view(), name='inicio'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home. views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/persona/add.html
{% extends 'base.html' %}
{% block title %} Añadir empleado {% endblock title %}

{% block content %} 
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Añadir empleado</h1>
        <form class="cell" action="" method="POST">{% csrf_token %}
            {{ form.as_p }}
            <button class="button success" type="submit">Agregar</button>
        </form>
    </div>
</div>

{% endblock content %}

templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Escribe el nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>
    <ul>
        {% for e in empleados %}
        <li>{{e}}</li>
        {% endfor %}
    </ul>
</h3>

templates/persona/delete.html
{% extends 'base.html' %}
{% block title %} Eliminar empleado {% endblock title %}

{% block content %} 
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar un empleado</h1>
            <form class="cell" method="post">{% csrf_token %}
                <div class="callout secondary">
                    <h5>¿Estás seguro de querer eliminar a {{ object.full_name }} como empleado de la empresa?</h5>
                    <button type="submit" class="alert button">Confirmar</button>
                  </div>
            </form>
    </div>
</div>

{% endblock content %}

templates/persona/detail_empleado.html
<h1>Detalle del empleado</h1>

{{ object }}

templates/persona/habilidades.html
<h1>Habilidades de empleados</h1>
<ul>

    {% for h in habilidades %}
        <li>
            {{ h }}
        </li>
    {% endfor %}    
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}
{% block title %} Listar empleados {% endblock title %}

{% block content %} 
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grd-x">
        <h1 class="cell">Listar empleados</h1>
        <div class="cell grid-x grid-margin-x">
            <form method="get">{% csrf_token %}
            <div class="cell large-5">
                <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="submit success button">Buscar</button>
            </div>
            </form>
        </div>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>Nombre</th>
                    <th width="150">Apellido</th>
                    <th width="150">Departamento</th>
                    <th width="150">Accion</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td><a class="button warning" href="{% url 'empleados_app:empleado_detail' e.id %}">Ver</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                  
                  {% if page_obj.has_previous %}
                  <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Anterior</a></li> 
                  {% endif %}
                  {% for pagina in paginator.page_range %}
                  
                  {% if pagina == page_obj.number  %} 
                  <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                  {% else %}
                  <li><a href="?page={{ pagina }}" aria-label="Page 2">{{ pagina }}</a></li>
                  {% endif %}
                    
                  
                  {% endfor %}
                  {% if page_obj.has_next %}
                  <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Next</a></li>
                  {% endif %}
                </ul>
            </nav> 
            {% endif %}
                
            
        </div>
    </div>
</div>


{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}
{% block title %} Listar personas por departamento {% endblock title %}
{% block content %} 
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">Empleados por area</div>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>Nombre</th>
                    <th width="150">Apellido</th>
                    <th width="150">Departamento</th>
                    <th width="150">Accion</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td><a class="button warning" href="{% url 'empleados_app:empleado_detail' e.id %}">Ver</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>

    </div>

</div>

{% endblock content %}

templates/persona/lista_empleados.html
{% extends 'base.html' %}
{% block title %} Listar empleados {% endblock title %}

{% block content %} 
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grd-x">
        <h1 class="cell">Listar empleados</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Departamento</th>
                    <th>Editar</th>
                    <th>Eliminar</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td><a class="button success" href="{% url 'empleados_app:modificar_empleado' e.id %}">Editar</a></td>
                    <td><a class="button alert" href="{% url 'empleados_app:eliminar_empleado' e.id %}">Eliminar</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                  
                  {% if page_obj.has_previous %}
                  <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Anterior</a></li> 
                  {% endif %}
                  {% for pagina in paginator.page_range %}
                  
                  {% if pagina == page_obj.number  %} 
                  <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                  {% else %}
                  <li><a href="?page={{ pagina }}" aria-label="Page 2">{{ pagina }}</a></li>
                  {% endif %}
                    
                  
                  {% endfor %}
                  {% if page_obj.has_next %}
                  <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Next</a></li>
                  {% endif %}
                </ul>
            </nav> 
            {% endif %}
                
            
        </div>
    </div>
</div>


{% endblock content %}

templates/persona/success.html
<h1>Registro creado!!</h1>

templates/persona/update.html
{% extends 'base.html' %}
{% block title %} Editar empleados {% endblock title %}

{% block content %} 
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Actualizar un empleado</h1>
        <div class="cell">
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <button class="button success" type="submit">Actualizar</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}