applications/departamento/urls.py
from django.urls import path
from . import views



app_name="departamento_app"
urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
    path(
        'departamento-lista/', 
        views.DepartamentoListView.as_view(), 
        name='departamento-lista'),
]

applications/empleados/urls.py
from django.urls import path
from . import views

app_name="empleados_app"

urlpatterns = [
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'),
    path(
        'listar-by-area/<shorname>',
         views.ListByAreaEmpleado.as_view(),
         name='empleados_area'),
    path(
        'lista-empleados-admin',
         views.ListaEmpleadosAdmin.as_view(),
         name='empleados_admin'),
    path('buscar-empleado', views.ListEmpleadosByKwords.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleados.as_view()),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'),
    path(
        'add-empleado/',
         views.EmpleadoCreateView.as_view(),
         name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
    path('', views.InicioView.as_view(), name='inicio'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home. views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50, blank="True")
    shor_name = models.CharField('Nombre Corto', max_length=20, unique=True, blank="True")
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name='Mi departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering=['-name']
        unique_together = ('name', 'shor_name')

    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shor_name
     

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import ListView
from .forms import NewDepartamentoForm
from applications.empleados.models import Empleado
from .models import Departamento

# Create your views here.


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name='departamentos'



class NewDepartamentoView(FormView):
    template_name='departamento/new_departamento.html'
    form_class=NewDepartamentoForm
    success_url='/'

    def form_valid(self, form):
        print('========Estoy en el form valid==========')
        depa=Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
        )
        depa.save

        nombre=form.cleaned_data['nombre']
        apellidos=form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellidos,
            job='1',
            departamento=depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}
{% block title %} Listar deprtamentos {% endblock title %}
{% block content %} 
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Departamentos de la empresa</h1>
        <div class="cell">
            <table>
                <tbody>
                    {% for departamentos in departamentos %}
                    <tr>
                        <td>{{ departamentos.name }}</td>
                        <td>{{ departamentos.shor_name }}</td>
                        <td><a class="button success" href="{% url 'empleados_app:empleados_area' departamentos.shor_name %}">Ver empleados</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

templates/departamento/new_departamento.html
<h1>Nuevo departamento</h1>

<form method="POST">{% csrf_token %}
    <h3>Datos empleados</h3>
    <p>
        {{form.nombre}}
    </p>
    <p>
        {{form.apellidos}}
    </p>
    <h3>Datos departamento</h3>
    <p>
        {{form.departamento}}
    </p>
    <p>
        {{form.shorname}}
    </p>

<button type="submit">Guardar</button>

</form>